export const getDataFromApi = () => {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(
        [
          {
            id: 1,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 12918,
            date: '2023-10-06',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 20
          },
          {
            id: 2,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 13919,
            date: '2023-10-08',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 200
          },
          {
            id: 3,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 13920,
            date: '2023-10-01',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 10
          },
          {
            id: 4,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 12921,
            date: '2023-10-04',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 5
          },
          {
            id: 5,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 13922,
            date: '2023-09-30',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 20
          },
          {
            id: 6,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 13923,
            date: '2023-10-01',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 15
          },
          {
            id: 7,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 13925,
            date: '2023-09-29',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 40
          },
          {
            id: 8,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 13925,
            date: '2023-09-28',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 33
          },
          {
            id: 9,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 13926,
            date: '2023-09-27',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 63
          },
          {
            id: 10,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 13926,
            date: '2023-09-26',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 27
          },
          {
            id: 11,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 13926,
            date: '2023-09-25',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 12
          },
          {
            id: 12,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 13926,
            date: '2023-09-25',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 42
          },
          {
            id: 13,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 13929,
            date: '2023-09-25',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 420
          },
          {
            id: 14,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 13929,
            date: '2023-10-05',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 88
          },
          {
            id: 15,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 13929,
            date: '2023-10-04',
            sku: 5,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 69
          },
          {
            id: 16,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 13932,
            date: '2023-10-03',
            sku: 5,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 59
          },
          {
            id: 17,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 13932,
            date: '2023-10-02',
            sku: 5,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 93
          },
          {
            id: 18,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 13932,
            date: '2023-10-06',
            sku: 5,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 59
          },
          {
            id: 19,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 13932,
            date: '2023-10-07',
            sku: 5,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 103
          },
          {
            id: 20,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 12918,
            date: '2023-10-06',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 200
          },
          {
            id: 21,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 12918,
            date: '2023-10-06',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 99
          },
          {
            id: 22,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 12918,
            date: '2023-10-06',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 103
          },
          {
            id: 23,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 12921,
            date: '2023-10-08',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 130
          },
          {
            id: 24,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 12921,
            date: '2023-10-08',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 160
          },
          {
            id: 25,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 12921,
            date: '2023-10-08',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 189
          },
          {
            id: 26,
            name: 'WMF 1500S+ russisch',
            path: 'TAT',
            group: 'WMF 1500 S+',
            machine_number: 12921,
            date: '2023-10-08',
            sku: 10,
            recipe: 'Капучино 400мл',
            cup_size: 'Regular',
            status: 'completed',
            summed_dispensings: 160
          },
        ]
      )
    }, 2000)
  })
}
